error | Testing logs | testFunc | /pages/test.js:1:1 | 2025-04-07T10:00:00Z
2025-04-07T13:09:01.579Z - ERROR - Error sending otp to user while login - Stack: ReferenceError: usser is not defined
    at handler (webpack-internal:///(api)/./pages/api/check-user.js:96:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.apiResolver (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async DevServer.runApi (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/next-server.js:514:9)
    at async Object.fn (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/next-server.js:828:35)
    at async Router.execute (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/router.js:243:32)
    at async DevServer.runImpl (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/base-server.js:432:29)
    at async DevServer.run (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/dev/next-dev-server.js:831:20)
    at async DevServer.handleRequestImpl (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/base-server.js:375:20)
    at async /home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/base-server.js:157:99 - Function: processRequest
{"level":50,"time":1744031341657,"pid":11427,"hostname":"ezbiz-12","message":"Error sending otp to user while login","stack":"ReferenceError: usser is not defined\n    at handler (webpack-internal:///(api)/./pages/api/check-user.js:96:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.apiResolver (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/api-utils/node.js:372:9)\n    at async DevServer.runApi (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/next-server.js:514:9)\n    at async Object.fn (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/next-server.js:828:35)\n    at async Router.execute (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/router.js:243:32)\n    at async DevServer.runImpl (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/base-server.js:432:29)\n    at async DevServer.run (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/dev/next-dev-server.js:831:20)\n    at async DevServer.handleRequestImpl (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/base-server.js:375:20)\n    at async /home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/base-server.js:157:99","function":"processRequest"}
2025-04-07T13:12:10.399Z - ERROR - Error sending otp to user while login - Stack: ReferenceError: usser is not defined - Function: processRequest
{"level":50,"time":1744031530400,"pid":11427,"hostname":"ezbiz-12","message":"Error sending otp to user while login","stack":"ReferenceError: usser is not defined\n    at handler (webpack-internal:///(api)/./pages/api/check-user.js:96:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.apiResolver (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/api-utils/node.js:372:9)\n    at async DevServer.runApi (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/next-server.js:514:9)\n    at async Object.fn (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/next-server.js:828:35)\n    at async Router.execute (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/router.js:243:32)\n    at async DevServer.runImpl (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/base-server.js:432:29)\n    at async DevServer.run (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/dev/next-dev-server.js:831:20)\n    at async DevServer.handleRequestImpl (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/base-server.js:375:20)\n    at async /home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/base-server.js:157:99","function":"processRequest"}
2025-04-07T13:15:11.720Z - ERROR - Error sending otp to user while login - Stack: ReferenceError: usser is not defined - Function: processRequest
{"level":50,"time":1744031711721,"pid":11427,"hostname":"ezbiz-12","message":"Error sending otp to user while login","stack":"ReferenceError: usser is not defined\n    at handler (webpack-internal:///(api)/./pages/api/check-user.js:96:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.apiResolver (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/api-utils/node.js:372:9)\n    at async DevServer.runApi (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/next-server.js:514:9)\n    at async Object.fn (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/next-server.js:828:35)\n    at async Router.execute (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/router.js:243:32)\n    at async DevServer.runImpl (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/base-server.js:432:29)\n    at async DevServer.run (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/dev/next-dev-server.js:831:20)\n    at async DevServer.handleRequestImpl (/home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/base-server.js:375:20)\n    at async /home/ezbiz-12/Documents/lalit/ezlnf/node_modules/next/dist/server/base-server.js:157:99","function":"processRequest"}
2025-04-08T10:31:55.512Z - ERROR - Error sending otp to user while login - Stack: Error: connect ETIMEDOUT
    at PromisePool.execute (/opt/lampp/htdocs/ezlnf/node_modules/mysql2/lib/promise/pool.js:54:22) - Function: processRequest
{"level":50,"time":1744108315518,"pid":16520,"hostname":"ezbiz3","message":"Error sending otp to user while login","stack":"Error: connect ETIMEDOUT\n    at PromisePool.execute (/opt/lampp/htdocs/ezlnf/node_modules/mysql2/lib/promise/pool.js:54:22)\n    at handler (webpack-internal:///(api)/./pages/api/check-user.js:46:70)\n    at Object.apiResolver (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/api-utils/node.js:372:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async DevServer.runApi (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:514:9)\n    at async Object.fn (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:828:35)\n    at async Router.execute (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/router.js:243:32)\n    at async DevServer.runImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:432:29)\n    at async DevServer.run (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/dev/next-dev-server.js:831:20)\n    at async DevServer.handleRequestImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:375:20)\n    at async /opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:157:99","function":"processRequest"}
2025-04-08T10:32:38.652Z - ERROR - Error sending otp to user while login - Stack: Error: connect ETIMEDOUT
    at PromisePool.execute (/opt/lampp/htdocs/ezlnf/node_modules/mysql2/lib/promise/pool.js:54:22) - Function: processRequest
{"level":50,"time":1744108358652,"pid":16520,"hostname":"ezbiz3","message":"Error sending otp to user while login","stack":"Error: connect ETIMEDOUT\n    at PromisePool.execute (/opt/lampp/htdocs/ezlnf/node_modules/mysql2/lib/promise/pool.js:54:22)\n    at handler (webpack-internal:///(api)/./pages/api/check-user.js:46:70)\n    at Object.apiResolver (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/api-utils/node.js:372:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async DevServer.runApi (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:514:9)\n    at async Object.fn (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:828:35)\n    at async Router.execute (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/router.js:243:32)\n    at async DevServer.runImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:432:29)\n    at async DevServer.run (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/dev/next-dev-server.js:831:20)\n    at async DevServer.handleRequestImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:375:20)\n    at async /opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:157:99","function":"processRequest"}
2025-04-09T08:23:06.903Z - ERROR - Error sending otp to user while login - Stack: Error: connect ETIMEDOUT
    at PromisePool.execute (/opt/lampp/htdocs/ezlnf/node_modules/mysql2/lib/promise/pool.js:54:22) - Function: processRequest
{"level":50,"time":1744186986906,"pid":18198,"hostname":"ezbiz3","message":"Error sending otp to user while login","stack":"Error: connect ETIMEDOUT\n    at PromisePool.execute (/opt/lampp/htdocs/ezlnf/node_modules/mysql2/lib/promise/pool.js:54:22)\n    at handler (webpack-internal:///(api)/./pages/api/check-user.js:46:70)\n    at Object.apiResolver (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/api-utils/node.js:372:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async DevServer.runApi (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:514:9)\n    at async Object.fn (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:828:35)\n    at async Router.execute (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/router.js:243:32)\n    at async DevServer.runImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:432:29)\n    at async DevServer.run (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/dev/next-dev-server.js:831:20)\n    at async DevServer.handleRequestImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:375:20)\n    at async /opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:157:99","function":"processRequest"}
2025-04-09T08:23:26.079Z - ERROR - Error sending otp to user while login - Stack: Error: connect ETIMEDOUT
    at PromisePool.execute (/opt/lampp/htdocs/ezlnf/node_modules/mysql2/lib/promise/pool.js:54:22) - Function: processRequest
{"level":50,"time":1744187006079,"pid":18198,"hostname":"ezbiz3","message":"Error sending otp to user while login","stack":"Error: connect ETIMEDOUT\n    at PromisePool.execute (/opt/lampp/htdocs/ezlnf/node_modules/mysql2/lib/promise/pool.js:54:22)\n    at handler (webpack-internal:///(api)/./pages/api/check-user.js:46:70)\n    at Object.apiResolver (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/api-utils/node.js:372:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async DevServer.runApi (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:514:9)\n    at async Object.fn (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:828:35)\n    at async Router.execute (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/router.js:243:32)\n    at async DevServer.runImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:432:29)\n    at async DevServer.run (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/dev/next-dev-server.js:831:20)\n    at async DevServer.handleRequestImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:375:20)\n    at async /opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:157:99","function":"processRequest"}
2025-04-09T12:35:34.179Z - ERROR - Error sending otp to user while login - Stack: Error: connect ETIMEDOUT
    at PromisePool.execute (/opt/lampp/htdocs/ezlnf/node_modules/mysql2/lib/promise/pool.js:54:22) - Function: processRequest
{"level":50,"time":1744202134181,"pid":4219,"hostname":"ezbiz3","message":"Error sending otp to user while login","stack":"Error: connect ETIMEDOUT\n    at PromisePool.execute (/opt/lampp/htdocs/ezlnf/node_modules/mysql2/lib/promise/pool.js:54:22)\n    at handler (webpack-internal:///(api)/./pages/api/check-user.js:46:70)\n    at Object.apiResolver (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/api-utils/node.js:372:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async DevServer.runApi (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:514:9)\n    at async Object.fn (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:828:35)\n    at async Router.execute (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/router.js:243:32)\n    at async DevServer.runImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:432:29)\n    at async DevServer.run (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/dev/next-dev-server.js:831:20)\n    at async DevServer.handleRequestImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:375:20)\n    at async /opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:157:99","function":"processRequest"}
2025-04-14T06:00:12.903Z - ERROR - Something went wrong - Stack:  - Function: paymentHandleer
{"level":50,"time":1744610412904,"pid":15100,"hostname":"LAPTOP-EMFHG45G","message":"Something went wrong","function":"paymentHandleer"}
2025-04-14T06:00:24.831Z - ERROR - Something went wrong - Stack:  - Function: paymentHandleer
{"level":50,"time":1744610424832,"pid":15100,"hostname":"LAPTOP-EMFHG45G","message":"Something went wrong","function":"paymentHandleer"}
2025-04-14T06:05:25.602Z - ERROR - Something went wrong - Stack:  - Function: paymentHandleer
{"level":50,"time":1744610725603,"pid":15100,"hostname":"LAPTOP-EMFHG45G","message":"Something went wrong","function":"paymentHandleer"}
2025-04-14T06:34:59.903Z - ERROR - Something went wrong - Stack: Error: `key_id` or `oauthToken` is mandatory
    at new Razorpay (C:\Users\TANISHQ\Documents\GitHub\ezlnf\node_modules\razorpay\dist\razorpay.js:34:13) - Function: paymentHandleer
{"level":50,"time":1744612499904,"pid":15740,"hostname":"LAPTOP-EMFHG45G","message":"Something went wrong","stack":"Error: `key_id` or `oauthToken` is mandatory\n    at new Razorpay (C:\\Users\\TANISHQ\\Documents\\GitHub\\ezlnf\\node_modules\\razorpay\\dist\\razorpay.js:34:13)\n    at handler (webpack-internal:///(api)/./pages/api/brand/payment.js:19:26)\n    at Object.apiResolver (C:\\Users\\TANISHQ\\Documents\\GitHub\\ezlnf\\node_modules\\next\\dist\\server\\api-utils\\node.js:372:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DevServer.runApi (C:\\Users\\TANISHQ\\Documents\\GitHub\\ezlnf\\node_modules\\next\\dist\\server\\next-server.js:514:9)\n    at async Object.fn (C:\\Users\\TANISHQ\\Documents\\GitHub\\ezlnf\\node_modules\\next\\dist\\server\\next-server.js:828:35)\n    at async Router.execute (C:\\Users\\TANISHQ\\Documents\\GitHub\\ezlnf\\node_modules\\next\\dist\\server\\router.js:243:32)\n    at async DevServer.runImpl (C:\\Users\\TANISHQ\\Documents\\GitHub\\ezlnf\\node_modules\\next\\dist\\server\\base-server.js:432:29)\n    at async DevServer.run (C:\\Users\\TANISHQ\\Documents\\GitHub\\ezlnf\\node_modules\\next\\dist\\server\\dev\\next-dev-server.js:831:20)\n    at async DevServer.handleRequestImpl (C:\\Users\\TANISHQ\\Documents\\GitHub\\ezlnf\\node_modules\\next\\dist\\server\\base-server.js:375:20)\n    at async C:\\Users\\TANISHQ\\Documents\\GitHub\\ezlnf\\node_modules\\next\\dist\\server\\base-server.js:157:99","function":"paymentHandleer"}
2025-04-14T06:36:03.919Z - ERROR - Something went wrong - Stack:  - Function: paymentHandleer
{"level":50,"time":1744612563920,"pid":15740,"hostname":"LAPTOP-EMFHG45G","message":"Something went wrong","function":"paymentHandleer"}
2025-04-14T06:36:51.699Z - ERROR - Something went wrong - Stack:  - Function: paymentHandleer
{"level":50,"time":1744612611699,"pid":15740,"hostname":"LAPTOP-EMFHG45G","message":"Something went wrong","function":"paymentHandleer"}
2025-04-14T07:10:22.970Z - ERROR - Something went wrong - Stack:  - Function: paymentHandleer
{"level":50,"time":1744614622972,"pid":11064,"hostname":"LAPTOP-EMFHG45G","message":"Something went wrong","function":"paymentHandleer"}
2025-04-14T07:11:29.926Z - ERROR - Something went wrong - Stack:  - Function: paymentHandleer
{"level":50,"time":1744614689927,"pid":11064,"hostname":"LAPTOP-EMFHG45G","message":"Something went wrong","function":"paymentHandleer"}
2025-04-14T07:11:54.935Z - ERROR - Something went wrong - Stack:  - Function: paymentHandleer
{"level":50,"time":1744614714937,"pid":11064,"hostname":"LAPTOP-EMFHG45G","message":"Something went wrong","function":"paymentHandleer"}
2025-04-14T07:14:01.815Z - ERROR - Something went wrong - Stack:  - Function: paymentHandleer
{"level":50,"time":1744614841816,"pid":11064,"hostname":"LAPTOP-EMFHG45G","message":"Something went wrong","function":"paymentHandleer"}
2025-04-17T06:39:01.083Z - ERROR - Error verifying OTP - Stack:  - Function: Unknown
{"level":50,"time":1744871941084,"pid":3958,"hostname":"ezbiz3","message":"Error verifying OTP"}
2025-04-17T06:42:27.175Z - ERROR - Error verifying OTP - Stack:  - Function: Unknown
{"level":50,"time":1744872147176,"pid":3958,"hostname":"ezbiz3","message":"Error verifying OTP"}
2025-04-17T06:42:59.978Z - ERROR - Error verifying OTP - Stack:  - Function: Unknown
{"level":50,"time":1744872179978,"pid":3958,"hostname":"ezbiz3","message":"Error verifying OTP"}
2025-04-17T06:43:47.031Z - ERROR - Error verifying OTP - Stack:  - Function: Unknown
{"level":50,"time":1744872227032,"pid":3958,"hostname":"ezbiz3","message":"Error verifying OTP"}
2025-04-17T06:44:27.937Z - ERROR - Error verifying OTP - Stack:  - Function: Unknown
{"level":50,"time":1744872267937,"pid":3958,"hostname":"ezbiz3","message":"Error verifying OTP"}
2025-04-17T06:45:30.781Z - ERROR - Error verifying OTP - Stack:  - Function: Unknown
{"level":50,"time":1744872330782,"pid":3958,"hostname":"ezbiz3","message":"Error verifying OTP"}
2025-04-17T07:02:17.869Z - ERROR - Error verifying OTP - Stack:  - Function: Unknown
{"level":50,"time":1744873337869,"pid":3958,"hostname":"ezbiz3","message":"Error verifying OTP"}
2025-04-18T07:48:10.746Z - ERROR - Error Verify OTP - Stack: ReferenceError: translateText is not defined
    at generateContactOwnerEmail (webpack-internal:///(api)/./lib/emailTemplates.js:196:31) - Function: sendingmail
{"level":50,"time":1744962490749,"pid":5381,"hostname":"ezbiz3","message":"Error Verify OTP","stack":"ReferenceError: translateText is not defined\n    at generateContactOwnerEmail (webpack-internal:///(api)/./lib/emailTemplates.js:196:31)\n    at handler (webpack-internal:///(api)/./pages/api/finderAuth/verifyOtp.js:121:125)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Object.apiResolver (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/api-utils/node.js:372:9)\n    at async DevServer.runApi (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:514:9)\n    at async Object.fn (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:828:35)\n    at async Router.execute (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/router.js:243:32)\n    at async DevServer.runImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:432:29)\n    at async DevServer.run (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/dev/next-dev-server.js:831:20)\n    at async DevServer.handleRequestImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:375:20)\n    at async /opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:157:99","function":"sendingmail"}
2025-05-13T11:39:09.860Z - ERROR - Error Verify OTP - Stack: ReferenceError: mailResponse is not defined
    at handler (webpack-internal:///(api)/./pages/api/finderAuth/verifyOtp.js:262:41) - Function: sendingmail
{"level":50,"time":1747136349863,"pid":28296,"hostname":"DESKTOP-L0EFPKF","message":"Error Verify OTP","stack":"ReferenceError: mailResponse is not defined\n    at handler (webpack-internal:///(api)/./pages/api/finderAuth/verifyOtp.js:262:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async eval (webpack-internal:///(api)/./utils/withMonitorLogger.js:12:13)\n    at async D:\\work\\LNF\\ezlnf\\node_modules\\@sentry\\nextjs\\build\\cjs\\common\\pages-router-instrumentation\\wrapApiHandlerWithSentry.js:85:28\n    at async Object.apiResolver (D:\\work\\LNF\\ezlnf\\node_modules\\next\\dist\\server\\api-utils\\node.js:372:9)\n    at async DevServer.runApi (D:\\work\\LNF\\ezlnf\\node_modules\\next\\dist\\server\\next-server.js:514:9)\n    at async Object.fn (D:\\work\\LNF\\ezlnf\\node_modules\\next\\dist\\server\\next-server.js:828:35)\n    at async Router.execute (D:\\work\\LNF\\ezlnf\\node_modules\\next\\dist\\server\\router.js:243:32)\n    at async DevServer.runImpl (D:\\work\\LNF\\ezlnf\\node_modules\\next\\dist\\server\\base-server.js:432:29)\n    at async DevServer.run (D:\\work\\LNF\\ezlnf\\node_modules\\next\\dist\\server\\dev\\next-dev-server.js:831:20)\n    at async DevServer.handleRequestImpl (D:\\work\\LNF\\ezlnf\\node_modules\\next\\dist\\server\\base-server.js:375:20)\n    at async D:\\work\\LNF\\ezlnf\\node_modules\\next\\dist\\server\\base-server.js:157:99","function":"sendingmail"}
2025-05-22T07:28:26.684Z - ERROR - Error sending otp - Stack: Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?, DATE_ADD(NOW(), INTERVAL 10 MINUTE), FALSE)' at line 2
    at PromisePool.query (/opt/lampp/htdocs/ezlnf/node_modules/mysql2/lib/promise/pool.js:36:22) - Function: otpsending
{"level":50,"time":1747898906685,"pid":7887,"hostname":"ezbiz3","message":"Error sending otp","stack":"Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?, DATE_ADD(NOW(), INTERVAL 10 MINUTE), FALSE)' at line 2\n    at PromisePool.query (/opt/lampp/htdocs/ezlnf/node_modules/mysql2/lib/promise/pool.js:36:22)\n    at handler (webpack-internal:///(api)/./pages/api/send-otp.js:55:55)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async eval (webpack-internal:///(api)/./utils/withMonitorLogger.js:12:13)\n    at async /opt/lampp/htdocs/ezlnf/node_modules/@sentry/nextjs/build/cjs/common/pages-router-instrumentation/wrapApiHandlerWithSentry.js:85:28\n    at async Object.apiResolver (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/api-utils/node.js:372:9)\n    at async DevServer.runApi (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:514:9)\n    at async Object.fn (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:828:35)\n    at async Router.execute (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/router.js:243:32)\n    at async DevServer.runImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:432:29)\n    at async DevServer.run (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/dev/next-dev-server.js:831:20)\n    at async DevServer.handleRequestImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:375:20)\n    at async /opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:157:99","function":"otpsending"}
2025-05-22T07:29:37.449Z - ERROR - Error sending otp - Stack: Error: Illegal arguments: undefined, number
    at _async (/opt/lampp/htdocs/ezlnf/node_modules/bcryptjs/dist/bcrypt.js:214:46) - Function: otpsending
{"level":50,"time":1747898977449,"pid":7887,"hostname":"ezbiz3","message":"Error sending otp","stack":"Error: Illegal arguments: undefined, number\n    at _async (/opt/lampp/htdocs/ezlnf/node_modules/bcryptjs/dist/bcrypt.js:214:46)\n    at /opt/lampp/htdocs/ezlnf/node_modules/bcryptjs/dist/bcrypt.js:223:17\n    at new Promise (<anonymous>)\n    at bcrypt.hash (/opt/lampp/htdocs/ezlnf/node_modules/bcryptjs/dist/bcrypt.js:222:20)\n    at handler (webpack-internal:///(api)/./pages/api/send-otp.js:53:86)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async eval (webpack-internal:///(api)/./utils/withMonitorLogger.js:12:13)\n    at async /opt/lampp/htdocs/ezlnf/node_modules/@sentry/nextjs/build/cjs/common/pages-router-instrumentation/wrapApiHandlerWithSentry.js:85:28\n    at async Object.apiResolver (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/api-utils/node.js:372:9)\n    at async DevServer.runApi (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:514:9)\n    at async Object.fn (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:828:35)\n    at async Router.execute (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/router.js:243:32)\n    at async DevServer.runImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:432:29)\n    at async DevServer.run (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/dev/next-dev-server.js:831:20)\n    at async DevServer.handleRequestImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:375:20)\n    at async /opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:157:99","function":"otpsending"}
2025-05-22T07:31:38.575Z - ERROR - Error sending otp - Stack: Error: Illegal arguments: undefined, number
    at _async (/opt/lampp/htdocs/ezlnf/node_modules/bcryptjs/dist/bcrypt.js:214:46) - Function: otpsending
{"level":50,"time":1747899098576,"pid":13287,"hostname":"ezbiz3","message":"Error sending otp","stack":"Error: Illegal arguments: undefined, number\n    at _async (/opt/lampp/htdocs/ezlnf/node_modules/bcryptjs/dist/bcrypt.js:214:46)\n    at /opt/lampp/htdocs/ezlnf/node_modules/bcryptjs/dist/bcrypt.js:223:17\n    at new Promise (<anonymous>)\n    at bcrypt.hash (/opt/lampp/htdocs/ezlnf/node_modules/bcryptjs/dist/bcrypt.js:222:20)\n    at handler (webpack-internal:///(api)/./pages/api/send-otp.js:53:86)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async eval (webpack-internal:///(api)/./utils/withMonitorLogger.js:12:13)\n    at async /opt/lampp/htdocs/ezlnf/node_modules/@sentry/nextjs/build/cjs/common/pages-router-instrumentation/wrapApiHandlerWithSentry.js:85:28\n    at async Object.apiResolver (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/api-utils/node.js:372:9)\n    at async DevServer.runApi (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:514:9)\n    at async Object.fn (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:828:35)\n    at async Router.execute (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/router.js:243:32)\n    at async DevServer.runImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:432:29)\n    at async DevServer.run (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/dev/next-dev-server.js:831:20)\n    at async DevServer.handleRequestImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:375:20)\n    at async /opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:157:99","function":"otpsending"}
2025-05-22T07:32:40.964Z - ERROR - Error sending otp - Stack: Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?, DATE_ADD(NOW(), INTERVAL 10 MINUTE), FALSE)' at line 2
    at PromisePool.query (/opt/lampp/htdocs/ezlnf/node_modules/mysql2/lib/promise/pool.js:36:22) - Function: otpsending
{"level":50,"time":1747899160965,"pid":13287,"hostname":"ezbiz3","message":"Error sending otp","stack":"Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?, DATE_ADD(NOW(), INTERVAL 10 MINUTE), FALSE)' at line 2\n    at PromisePool.query (/opt/lampp/htdocs/ezlnf/node_modules/mysql2/lib/promise/pool.js:36:22)\n    at handler (webpack-internal:///(api)/./pages/api/send-otp.js:53:55)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async eval (webpack-internal:///(api)/./utils/withMonitorLogger.js:12:13)\n    at async /opt/lampp/htdocs/ezlnf/node_modules/@sentry/nextjs/build/cjs/common/pages-router-instrumentation/wrapApiHandlerWithSentry.js:85:28\n    at async Object.apiResolver (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/api-utils/node.js:372:9)\n    at async DevServer.runApi (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:514:9)\n    at async Object.fn (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:828:35)\n    at async Router.execute (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/router.js:243:32)\n    at async DevServer.runImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:432:29)\n    at async DevServer.run (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/dev/next-dev-server.js:831:20)\n    at async DevServer.handleRequestImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:375:20)\n    at async /opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:157:99","function":"otpsending"}
2025-05-22T07:33:19.947Z - ERROR - Error sending otp - Stack: Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?, DATE_ADD(NOW(), INTERVAL 10 MINUTE), FALSE)' at line 2
    at PromisePool.query (/opt/lampp/htdocs/ezlnf/node_modules/mysql2/lib/promise/pool.js:36:22) - Function: otpsending
{"level":50,"time":1747899199948,"pid":13287,"hostname":"ezbiz3","message":"Error sending otp","stack":"Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?, DATE_ADD(NOW(), INTERVAL 10 MINUTE), FALSE)' at line 2\n    at PromisePool.query (/opt/lampp/htdocs/ezlnf/node_modules/mysql2/lib/promise/pool.js:36:22)\n    at handler (webpack-internal:///(api)/./pages/api/send-otp.js:53:55)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async eval (webpack-internal:///(api)/./utils/withMonitorLogger.js:12:13)\n    at async /opt/lampp/htdocs/ezlnf/node_modules/@sentry/nextjs/build/cjs/common/pages-router-instrumentation/wrapApiHandlerWithSentry.js:85:28\n    at async Object.apiResolver (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/api-utils/node.js:372:9)\n    at async DevServer.runApi (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:514:9)\n    at async Object.fn (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:828:35)\n    at async Router.execute (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/router.js:243:32)\n    at async DevServer.runImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:432:29)\n    at async DevServer.run (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/dev/next-dev-server.js:831:20)\n    at async DevServer.handleRequestImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:375:20)\n    at async /opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:157:99","function":"otpsending"}
2025-05-22T07:34:44.807Z - ERROR - Error sending otp - Stack: Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?, DATE_ADD(NOW(), INTERVAL 10 MINUTE), FALSE)' at line 2
    at PromisePool.query (/opt/lampp/htdocs/ezlnf/node_modules/mysql2/lib/promise/pool.js:36:22) - Function: otpsending
{"level":50,"time":1747899284807,"pid":13287,"hostname":"ezbiz3","message":"Error sending otp","stack":"Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?, DATE_ADD(NOW(), INTERVAL 10 MINUTE), FALSE)' at line 2\n    at PromisePool.query (/opt/lampp/htdocs/ezlnf/node_modules/mysql2/lib/promise/pool.js:36:22)\n    at handler (webpack-internal:///(api)/./pages/api/send-otp.js:53:55)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async eval (webpack-internal:///(api)/./utils/withMonitorLogger.js:12:13)\n    at async /opt/lampp/htdocs/ezlnf/node_modules/@sentry/nextjs/build/cjs/common/pages-router-instrumentation/wrapApiHandlerWithSentry.js:85:28\n    at async Object.apiResolver (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/api-utils/node.js:372:9)\n    at async DevServer.runApi (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:514:9)\n    at async Object.fn (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/next-server.js:828:35)\n    at async Router.execute (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/router.js:243:32)\n    at async DevServer.runImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:432:29)\n    at async DevServer.run (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/dev/next-dev-server.js:831:20)\n    at async DevServer.handleRequestImpl (/opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:375:20)\n    at async /opt/lampp/htdocs/ezlnf/node_modules/next/dist/server/base-server.js:157:99","function":"otpsending"}
